import type { Metadata } from "next";
import { Montserrat } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/providers/theme-provider";
import { TopLoaderBarProvider } from "@/providers/toploaderbar-provider";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "@/components/ui/sonner";

const monsterrat = Montserrat({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: {
    default: "CordXplorer",
    template: "%s | CordXplorer",
  },
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html
      lang="en"
      suppressHydrationWarning
      className="min-w-[300px]"
    >
      <body className={monsterrat.className}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
          storageKey="theme"
        >
          <TopLoaderBarProvider>
            <Toaster
              position="top-right"
              toastOptions={{
                className: "border-primary",
              }}
            />
            <SessionProvider>{children}</SessionProvider>
          </TopLoaderBarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
