import type { Metadata } from "next";
import { Quicksand } from "next/font/google";
import "./globals.css";

import { ThemeProvider } from "@/providers/theme-provider";
import { TopLoaderBarProvider } from "@/providers/toploaderbar-provider";
import { SessionProvider } from "next-auth/react";
import { Toaster } from "@/components/ui/sonner";
import { cn } from "@/lib/utils";

const quicksand = Quicksand({
  weight: ["300", "400", "700", "500", "600"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: {
    default: "CordXplorer",
    template: "%s | CordXplorer",
  },
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" suppressHydrationWarning className="subpixel-antialiased">
      <body className={cn("bg-background-liniar", quicksand.className)}>
        <ThemeProvider
          attribute="class"
          defaultTheme="dark"
          enableSystem
          disableTransitionOnChange
          storageKey="theme"
        >
          <TopLoaderBarProvider>
            <Toaster
              position="top-right"
              toastOptions={{
                className: "border-primary",
              }}
            />
            <SessionProvider>{children}</SessionProvider>
          </TopLoaderBarProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
